---
sudo: required # docker
services:
  - docker
addons:
  apt:
    packages:
      - cmake
      - pkg-config
      - gkrellm
      - libgtk2.0-dev
jobs:
  include:
    - env: [ ACTION=build ]
      compiler: gcc
    - env: [ ACTION=build ]
      compiler: clang
    - env: [ ACTION=omnilint ]
    - env: [ ACTION=format ]
language: c
script:
  - |
    if [ "$ACTION" = omnilint ]; then
        docker pull lpenz/omnilint
        docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
    elif [ "$ACTION" = format ]; then
        docker build -t image:latest .
        docker run -v $PWD:/home/user/work -e MY_UID=$UID image find . -name '*.[ch]' -o -name '*.cc' -exec clang-format '-style={BasedOnStyle: google, IndentWidth: 4}' -i {} +
        git diff --exit-code
    else
        SRC_DIR=$PWD
        mkdir ../build
        cd ../build
        cmake "$SRC_DIR"
        make
    fi
