---
sudo: true # gkrellm
addons:
  apt:
    packages:
      - pkg-config
      - gkrellm # https://github.com/travis-ci/apt-package-whitelist/issues/2505
      - libgtk2.0-dev
      - txt2tags
      - devscripts
language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gkrellm
script:
  - make
  - dpkg-buildpackage -uc -us
deploy:
  provider: packagecloud
  repository: lpenz
  username: lpenz
  token:
    secure: g26ixB08/ggWL3aMXIjJAGZq0ALhjKcwPiXCTYOFDA8A6MpYALdKrl6Tm7k2NweVU5AYseIzJ/ufF9R/4MTGk8u6V/f8HK7tVy/1wu/+ne1va8E5WJR8ZNuMjzkTnCaik7RnT2Qri06v2TlC4rRJwc6N+iB62R4XvQFA/rq5MtU=
  dist: debian/jessie
  local-dir: '..'
  package_glob: '*.deb'
