---
sudo: required # docker
services:
  - docker
addons:
  apt:
    packages:
      - cmake
      - pkg-config
      - gkrellm
      - libgtk2.0-dev
jobs:
  include:
    - env: [ ACTION=build ]
      compiler: gcc
    - env: [ ACTION=build ]
      compiler: clang
    - env: [ ACTION=omnilint ]
      language: generic
      script:
        - docker pull lpenz/omnilint
        - docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
    - env: [ ACTION=format ]
      language: generic
      script:
        - docker pull debian:stretch
        - docker run -d --name debian -v "$PWD:$PWD" debian:stretch sleep 9999999999
        - docker exec -t debian /bin/bash -c "apt-get update && apt-get install -y --no-install-recommends clang-format"
        - docker exec -t debian find "$PWD" \( -name '*.[ch]' -o -name '*.cc' \) -exec clang-format -i {} +
        - git diff --exit-code
language: c
script:
  - SRC_DIR=$PWD
  - mkdir ../build
  - cd ../build
  - cmake "$SRC_DIR"
  - make
