---
addons:
  apt:
    packages:
      - pkg-config
      - gkrellm
      - libgtk2.0-dev
      - devscripts
      - fakeroot
      - debhelper
      - build-essential
      - ruby
      - txt2tags
language: c
compiler:
   - gcc
script:
  - make
  - dpkg-buildpackage -uc -us
deploy:
  provider: packagecloud
  repository: lpenz
  username: lpenz
  token:
    secure: g26ixB08/ggWL3aMXIjJAGZq0ALhjKcwPiXCTYOFDA8A6MpYALdKrl6Tm7k2NweVU5AYseIzJ/ufF9R/4MTGk8u6V/f8HK7tVy/1wu/+ne1va8E5WJR8ZNuMjzkTnCaik7RnT2Qri06v2TlC4rRJwc6N+iB62R4XvQFA/rq5MtU=
  dist: debian/stretch
  local-dir: '..'
  package_glob: '*.deb'
  on:
    tags: true
    condition: "$CC = gcc"
